// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RWS_LBE_Transaction.Data;

#nullable disable

namespace RWS_LBE_Transaction.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250616030249_AddMissingChanges")]
    partial class AddMissingChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RWS_LBE_Transaction.Models.AuditLog", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("ActorID")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("actor_id");

                    b.Property<string>("ClientIP")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("client_ip");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<long>("LatencyMs")
                        .HasColumnType("bigint")
                        .HasColumnName("latency_ms");

                    b.Property<string>("Method")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("method");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("path");

                    b.Property<string>("RequestBody")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("request_body");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_body");

                    b.Property<long>("StatusCode")
                        .HasColumnType("bigint")
                        .HasColumnName("status_code");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_agent");

                    b.HasKey("ID");

                    b.ToTable("audit_logs");
                });

            modelBuilder.Entity("RWS_LBE_Transaction.Models.SysChannel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("app_id")
                        .HasAnnotation("Relational:JsonPropertyName", "app_id");

                    b.Property<string>("AppKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("app_key")
                        .HasAnnotation("Relational:JsonPropertyName", "app_key");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("create_time")
                        .HasAnnotation("Relational:JsonPropertyName", "create_time");

                    b.Property<string>("SigMethod")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("sig_method")
                        .HasAnnotation("Relational:JsonPropertyName", "sig_method");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("update_time")
                        .HasAnnotation("Relational:JsonPropertyName", "update_time");

                    b.HasKey("Id");

                    b.ToTable("sys_channel");
                });
#pragma warning restore 612, 618
        }
    }
}
